### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Migan178** [SaidBySolo/blue-archive-bundle-downloader#1]
i am using Ubuntu 20.04 LTS Desktop and python 3.8.10 and venv

**Comment by SaidBySolo** [comment]
Not A Bug.

https://github.com/SaidBySolo/blue-archive-bundle-downloader/blob/3ca0cf2ea34fc25e2868905523e4a8af002f68e1/main.py#L14

It seems that the type hint is the problem.

**Comment by Migan178** [comment]
Got it.
